site_name: pyFlowChile
site_url: https://mariofix.github.io/pyflowcl
repo_url: https://github.com/mariofix/pyflowcl
repo_name: mariofix/pyflowcl
site_description: Documentacion para pyFlowCl
site_author: mariofix <mariofix@proton.me>
copyright: "MIT License"

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
    logo: material/contactless-payment
    alternate: material/translate-variant
  font:
    text: Ubuntu

extra:
  alternate:
    - name: Español
      link: /
      lang: es
  scope: /

plugins:
  - mkdocstrings
  - social

nav:
  - Inicio: index.md
  - Cómo Usar: uso.md
  - Referencia:
      - Payment: apiclient-payment.md
      - Refund: apiclient-refund.md
      - ApiClient: apiclient.md
      - Modelos: models.md
  - Integraciones:
      - Django Payments: django-payments.md
      - Merchants: merchants.md
  - Colabora: contributing.md
  - Registro de Cambios: changelog.md

markdown_extensions:
  abbr:
  toc:
    permalink: true
  admonition:
  extra:
  attr_list:
  def_list:
  footnotes:
  tables:
  md_in_html:
  pymdownx.superfences:
  pymdownx.details:
  pymdownx.snippets:
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  pymdownx.highlight:
    anchor_linenums: true
    auto_title: true
  pymdownx.inlinehilite:
