site_name: pyFlowChile
site_url: https://mariofix.github.io/pyflowcl
repo_url: https://github.com/mariofix/pyflowcl
repo_name: mariofix/pyflowcl
site_description: Documentacion para pyFlowCl
site_author: mariofix <yo@mariofix.com>
copyright: "MIT License"
edit_uri: ""

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tracking
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
    logo: material/contactless-payment
  font:
    text: Montserrat

plugins:
  - mkdocstrings

nav:
  - Inicio: index.md
  - Cómo Usar: uso.md
  - Referencia:
      - ApiClient: apiclient.md
      - Payment: apiclient-payment.md
      - Refund: apiclient-refund.md
      - Modelos: models.md
  - Django Payments: django-payments.md
  - Merchants: merchants.md
  - Colabora: contributing.md
  - Registro de Cambios: changelog.md

markdown_extensions:
  toc:
    permalink: true
  markdown.extensions.codehilite:
    guess_lang: false
  mdx_include:
    base_path: docs
  admonition:
  codehilite:
  extra:
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ""
  pymdownx.tabbed:
    alternate_style: true
  attr_list:
  md_in_html:
